### ISSUE TITLE
Add energy meter?

### ISSUE THREAD

**Issue by 86hakan** [filipvh/hass-nhc2#28]
Is there any plan to integrate energy meters?

I have many meters in my installation and can be a test person.

**Comment by Gavergracht** [comment]
It would be cool to get the digital meter implemented

**Comment by Tjaardv** [comment]
> It would be cool to get the digital meter implemented

You can install the DSRM integration in HASS

**Comment by 86hakan** [comment]
Ok. But what i want to integrate is the meters from niko home control.

**Comment by Gavergracht** [comment]
yes, that is what @86hakan

**Comment by joleys** [comment]
I was able to get the electrical energy meter (with clamps) into HA.  At the moment I get the real-time measurement with the standard 2 second update interval.  However, for the HA Energy functionality, a summation or kWh value is needed.  The math for that needs to be added.

**Comment by Gavergracht** [comment]
How did you do it ?

**Comment by joleys** [comment]
> How did you do it ?

On my laptop is a copy of HA for development purposes.  I've copied the NHC2 integration form @filipvh and changed all dependencies to use local files.  This gets rid of the nhc2-coco dependency and allows for flexible testing.
I've coded an extension of both hass-nhc2 and nhc2-coco to initiate the MQTT message generation and process the results.  Since I'm not a GitHub push/pull hero, it will take some time to create the pull request.  I'll try to find some spare time this weekend.

**Comment by joleys** [comment]
Pull request issued.
In addition to the code posted, I've added the following in configuration.yaml:

```
sensor:
  - platform: integration
    source: sensor.elektriciteitsmeting
    name: energy_elektriciteit
    unit_prefix: k
    round: 3
    method: left

utility_meter:
  energy_daily:
    source: sensor.energy_elektriciteit
    cycle: daily
  energy_monthly:
    source: sensor.energy_elektriciteit
    cycle: monthly
```

This will calculate daily and monthly totalizers (kWh).
Source: [https://community.home-assistant.io/t/2021-8-new-energy-feature-in-ha-conversion-from-w-to-kwh/328830](https://community.home-assistant.io/t/2021-8-new-energy-feature-in-ha-conversion-from-w-to-kwh/328830)
